//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class KisiBakiye
    {
        public int ID { get; set; }
        public string Adı { get; set; }
        public Nullable<decimal> Bakiye { get; set; }
        public Nullable<short> Yas { get; set; }
    }
}
